### ISSUE TITLE
 cms --config-file /home/alice.yaml get-export-data-key-b64错误

### ISSUE THREAD

**Issue by qinjuana** [secretflow/capsule-manager#15]
(capsule-manager-sdk1) root@wangweifengqinjuann2-4778:/home# cms --config-file /home/alice.yaml get-export-data-key-b64
Traceback (most recent call last):
  File "/root/miniconda3/envs/capsule-manager-sdk1/bin/cms", line 8, in <module>
    sys.exit(cms())
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/cli/cms.py", line 263, in get_export_data_key_b64
    data_key = ctx.obj.get_export_data_key_b64(
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/sdc/capsule_manager_frame.py", line 607, in get_export_data_key_b64
    raise CapsuleManagerError(
sdc.error.CapsuleManagerError: CapsuleManager server error code: 13, error message: err code: Assert err; err detail: model_uuid xgb_model is not the same as expected; location: [line = 346, file = capsule-manager/src/core/model/request.rs]
请看下配置文件哪里配置错误？
get_export_data_key_b64:
  # (required) str
  party_id: "R6LXWH5TKM5KCWOUGA2OZKUZPW3HUV4WCYIPPNXBS52PGNAD5VLQ"
  # (required) str
  resource_uri: xgb_model
  # (required) str
  data_export_certificate_file: vote-result.json

**Comment by zhongtianq** [comment]
@qinjuana 确认一下你的resource_uri与你进行计算以及导出请求发起的时候都是保持一致的，我们给的demo里面应该是model_uuid。看起来你指定了resource_uri为xgb_model，由于缺少前面步骤的上下文，所以我不确定你是否都手动进行了修改。请先自行检查一下是否一致

**Comment by zhongtianq** [comment]
文档说明上做了一些更新，官网文档稍后会同步更新，感谢提问，我们会进一步完善文档～
